development:
  adapter: postgresql
  host: localhost
  database: tv-episodes_development

test: &test
  adapter: postgresql
  host: localhost
  database: tv-episodes_test

production:
  adapter: postgresql
  host: localhost
  database: tv-episodes_development
